services:
  backend:
    build: .
    ports:
      - 5000:8080
      - 9229:9229 # for debugging
    volumes:
      - .:/app # bind mounts - share a directory from the host's filesystem into the container
      - /app/node_modules # anonymous volume
    command: npm run start:docker # override the command in Dockerfile
    environment: # environment variable
      PORT: 8080
