name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  APP_NAME: demo-app

jobs:
  build-and-deploy:
    name: Build Docker image and Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository code'
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2.1.3
        with:
          # Service account based authentication
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Configure the Google Cloud SDK in the GitHub Actions environment (gcloud and gsutil)
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      # Build and push image to Google Container Registry (GCR)

      # # using `gcloud builds submit` command
      # - name: Build
      #   run: |
      #     gcloud builds submit \
      #     --tag gcr.io/$PROJECT_ID/$APP_NAME:$GITHUB_SHA

      # Build the image on GitHub Actions Runner and push it to GCR
      - name: Login to ECR
        uses: docker/login-action@v3.2.0
        with:
          registry: gcr.io
          # Service account based authentication
          username: _json_key
          password: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Build and push to ECR
        uses: docker/build-push-action@v5.4.0
        with:
          push: true
          tags: gcr.io/$PROJECT_ID/$APP_NAME:$GITHUB_SHA

      # Deploy image to Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy $APP_NAME \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --image gcr.io/$PROJECT_ID/$APP_NAME:$GITHUB_SHA \
          --port=3000 \
          --command="npm,run,dev"
