name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  APP_NAME: demo-app

jobs:
  build-and-deploy:
    name: Build Docker image and Deploy to Cloud Run
    runs-on: ubuntu-latest
    env:
      IMAGE: gcr.io/$PROJECT_ID/$APP_NAME:$GITHUB_SHA
    steps:
      # Clone the GitHub repository
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.3
        with:
          # Service account based authentication
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Configure the Google Cloud SDK in the GitHub Actions environment (gcloud and gsutil)
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      ###
      # Build and push image to GCR using `gcloud builds submit` command
      ###
      # - name: Build
      #   run: |
      #     gcloud builds submit \
      #     --tag ${{ env.IMAGE }}

      ###
      # Build the image on GitHub Actions Runner and push it to GCR
      ###

      # Setting up Docker Buildx (required for build-push action)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to GCR
        uses: docker/login-action@v3.2.0
        with:
          registry: gcr.io
          # Service account based authentication
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}

      # Build the Docker image and push it to GCR
      - name: Build and push to GCR
        uses: docker/build-push-action@v5.4.0
        with:
          push: true
          tags: ${{ env.IMAGE }}

      # Deploy image to Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy $APP_NAME \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --image ${{ env.IMAGE }} \
          --port=3000 \
          --command="npm,run,dev"
